### ISSUE TITLE
FIX NULLPOINT (Problems with OneToOne Relationship(MemberCard))

### ISSUE THREAD

**Issue by SDiamante13** [SalenaLuu/Tastylab#8]
https://github.com/CodingSeahorse/Tastylab/blob/911585de011593388ec0f31ad037813d2e492435/src/main/java/com/codingseahorse/tastylab/model/member/Member.java#L99

Change Member to the following:

```java
    @NonNull
    @OneToOne
    @JoinColumn(name = "memberCardId", referencedColumnName = "member_card_id")
    private MemberCard membercard;
```

And in MemberCard remove the reference to Member.

~~@OneToOne(
            cascade = ALL,
            fetch = LAZY
    )
    @JoinColumn(
            name = "member_id",
            referencedColumnName = "member_id",
            foreignKey = @ForeignKey(
                    name = "member_card_fk"
            )
    )
    private Member member;~~

You only need to reference in one direction. So a Member has a member card. In the member table there will be a member_card_id that will let you know where to find the member card. I replaced this code and the test passed.

**Comment by SalenaLuu** [comment]
Fixed issue. Thanks Steven ! :)
